### ISSUE TITLE
Chapter Page UI 추가

### ISSUE THREAD

**Issue by GoodGoodJM** [NihonGOSamurai/Nihon-GO#1]
Chpater를 수정하는데 필요한 Page를 작업한다.
현재 단계에서는 UI와 UI의 동작만 작업한다. 데이터 저장 등의 로직은 해당 이슈에서 작업하지 않는다.

DashBoard Page(기본 페이지)에서 Chapter를 누르면 해당 ChapterID로 라우팅하여 Chpater페이지에 라우팅 되어야 한다.(url 예: `~/chapter/{page_id}`)

해당 이슈의 UI의 동작 에는 `한자/단어 추가 팝업`이 포함되므로 이 또한 작업하여야 한다.

## Chpater Page에 관하여

ChapterPage는 해당 챕터에 있는 Item들을 보여주는 페이지이다.

Item(단어)들은 PC상에서는 2 column으로, Mobile에서는 1 column으로 표시되어야 한다.

항상 맨 첫번째 아이템은 `단어 추가`의 동작을 해야하며, 해당 아이템을 클릭할 시 `한자/단어 추가 팝업`이 표시되어야 한다.(Chpater를 수정하는데 필요한 Page를 작업한다.
현재 단계에서는 UI와 UI의 동작만 작업한다. 데이터 저장 등의 로직은 해당 이슈에서 작업하지 않는다.

DashBoard Page(기본 페이지)에서 Chapter를 누르면 해당 ChapterID로 라우팅하여 Chpater페이지에 라우팅 되어야 한다.(url 예: `~/chapter/{page_id}`)

해당 이슈의 UI의 동작 에는 `한자/단어 추가 팝업`이 포함되므로 이 또한 작업하여야 한다.

## Chpater Page에 관하여

ChapterPage는 해당 챕터에 있는 Item들을 보여주는 페이지이다.

Item(단어)들은 PC상에서는 2 column으로, Mobile에서는 1 column으로 표시되어야 한다.

항상 맨 첫번째 Item은 `단어 추가`의 동작을 해야하며, 해당 아이템을 클릭할 시 `한자/단어 추가 팝업`이 표시되어야 한다. `단어 추가` 동작 Item은 다른 Item(단어) 같은 크기를 가지나, 외각선만 있고 빈 것 처럼 보여야 하고, 가운데에 글자로 `+`가 표시되어야한다.
(MainPage의 `챕터 추가` 버튼 참조)

## 참고

![Imgur](https://i.imgur.com/MGwS8eK.png)
![Imgur](https://i.imgur.com/kwz2Lug.png)

**Comment by puwon2a62** [comment]
확인했습니다.

**Comment by puwon2a62** [comment]
확인했습니다.

**Comment by GoodGoodJM** [comment]
Pull Request에서 머지 할 당시, default branch가 master여서 닫히지 않아 수동으로 닫습니다.
